services:
  - type: web
    name: supplier-management-api
    runtime: node
    buildCommand: pnpm install && pnpm turbo build --filter=@workspace/database... --filter=backend-api...
    startCommand: cd apps/backend-api && NODE_PATH=./node_modules NODE_ENV=development pnpm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false 
  
  - type: web
    name: supplier-drizzle-studio
    runtime: node
    buildCommand: pnpm install && pnpm turbo build --filter=@workspace/database...
    startCommand: cd packages/database && pnpm db:studio
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 3333
      - key: DATABASE_URL
        sync: false