services:
  - type: web
    name: supplier-management-api
    runtime: node
    buildCommand: pnpm install && pnpm turbo build --filter=@workspace/database... --filter=backend-api...
    startCommand: cd apps/backend-api && NODE_PATH=./node_modules pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false 